# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('location_type', models.CharField(max_length=40)),
                ('locality', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('identificador',),
                'verbose_name': 'maps',
            },
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name=b'titulo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('data_criacao',),
                'verbose_name': 'localidade',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.AddField(
            model_name='maps',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.Ordem'),
        ),
    ]
