# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160821_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='status',
            field=models.CharField(choices=[(b'A', b'Andamento'), (b'F', b'Atualizado'), (b'X', b'N\xc3\xa3o Localizado'), (b'N', b'Novo')], default=b'N', max_length=1),
        ),
    ]
