# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_maps_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='exibe_address',
            field=models.CharField(choices=[(b'S', b'Show'), (b'E', b'Show Editable')], default=b'S', max_length=1),
        ),
        migrations.AddField(
            model_name='ordem',
            name='exibe_identificador',
            field=models.CharField(choices=[(b'S', b'Show'), (b'H', b'Hide')], default=b'S', max_length=1),
        ),
    ]
