# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160829_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
