# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='file',
            field=models.FileField(blank=True, upload_to=b'/Users/andrel/Desenvolvimento/Pessoal/grg/maps-django/maps/media'),
        ),
    ]
